services:
  web:
    build:
      context: app
      dockerfile: Dockerfile.prod
    command: gunicorn 'config.wsgi:application' --bind=0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/staticfiles/
      - media_volume:/home/app/mediafiles/
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/staticfiles/
      - media_volume:/home/app/mediafiles/
    depends_on:
      - web
volumes:
  db-data:
  static_volume:
  media_volume:


