services:
  web:
    build:
      context: backend
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py test"
    ports:
      - 8000:8000
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
  redis:
    restart: unless-stopped
    image: redis:8.0-rc1-alpine3.21
    ports:
      - 6379:6379
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


