# Generated by Django 5.1.3 on 2025-04-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='related_object',
            new_name='content_object',
        ),
    ]
