# Generated by Django 5.1.3 on 2025-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/default_avatars/002-girl.png', null=True, upload_to='avatars'),
        ),
    ]
