# Generated by Django 5.1.3 on 2025-04-26 16:17

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=utils.utils.get_random_avatar, max_length=500, null=True, upload_to='images/avatars/'),
        ),
    ]
