# Generated by Django 5.1.3 on 2025-04-04 03:03

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_content_quill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
