# Generated by Django 5.1.3 on 2025-04-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='thumnail_post/defaultthumbnail.jpg', upload_to='thumnail_post'),
        ),
    ]
