# Generated by Django 5.1.3 on 2025-04-04 02:59

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_quillpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_quill',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
