# Generated by Django 5.1.3 on 2025-04-04 03:35

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='quillpost',
            name='description',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AddField(
            model_name='quillpost',
            name='title',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='quillpost',
            name='content',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
