# Generated by Django 5.1.3 on 2025-04-04 06:40

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_quillpost_description_quillpost_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_quill',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
