# Generated by Django 5.1.3 on 2025-04-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='thumnail_post/default.jpg', upload_to='thumnail_post'),
        ),
    ]
