# Generated by Django 5.1.3 on 2025-04-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_remove_post_content_post_content_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_text',
            new_name='content',
        ),
    ]
