# Generated by Django 5.1.3 on 2025-04-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_alter_post_content'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvotes',
            new_name='votes',
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to='posts.post')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.profile')),
            ],
            options={
                'unique_together': {('voter', 'post')},
            },
        ),
    ]
