# Generated by Django 5.1.3 on 2025-04-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_rename_upvotes_post_votes_postvote'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postvote',
            old_name='voter',
            new_name='voted_by',
        ),
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together={('voted_by', 'post')},
        ),
    ]
