# Generated by Django 5.1.3 on 2025-04-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_rename_voter_postvote_voted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='/static/defaultthumnail/analog-digital-learning-harmony_882186-15242.avif', upload_to='thumnail_post'),
        ),
    ]
