# Generated by Django 5.1.3 on 2025-04-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_text',
            field=models.TextField(blank=True),
        ),
    ]
