# Generated by Django 5.1.3 on 2025-04-12 08:03

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_post_content_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_text',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
