# Generated by Django 5.1.3 on 2025-04-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_alter_post_thumbnail_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='/media/defaultthumnail/persons-hands-are-writing-large-open-book-there-are-two-pens-mug-tea-some-floral-plants-table_1031128-17746.avif', upload_to='thumnail_post'),
        ),
    ]
