# Generated by Django 5.1.3 on 2025-04-24 08:43

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=utils.utils.get_random_thumbnail, null=True, upload_to='thumnail_post'),
        ),
    ]
