# Generated by Django 5.1.3 on 2025-04-25 09:53

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=utils.utils.get_random_thumbnail, max_length=500, null=True, upload_to='images/thumnail_posts/'),
        ),
    ]
