# Generated by Django 5.1.3 on 2025-04-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_text',
        ),
    ]
