# Generated by Django 5.1.3 on 2025-05-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_remove_post_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản')], default='draft', max_length=10),
        ),
    ]
