# Generated by Django 5.1.3 on 2025-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0060_post_published_at_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_published_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
